spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username:
    password:
    schema:
      - classpath:schema.sql
#    data:
#      - classpath:sql/data/*.sql

